#!/bin/bash
pip install qgrid
jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter serverextension enable --py jupyterlab
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False
jupyter labextension install @8080labs/qgrid