#!/bin/bash
pip install --upgrade qgrid==1.1.1
jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter serverextension enable --py jupyterlab
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False
jupyter labextension install qgrid2 --minimize=False